### ISSUE TITLE
Verify Permissions button appears to do nothing / 500 internal server error

### ISSUE THREAD

**Issue by jkittle** [drkchiloll/IMPERIUM#1]
I created an account for my CUCM, clicked the 'TEST' button and the icon turns green, however nothing happens when I click the 'Verify Permissions' button.  Another symptom / may be the same cause, may not - When I execute a search and it lists my phones, I get a 500 internal server error back. I'm on CUCM 11.5

**Comment by drkchiloll** [comment]
Something I did Leave out..but am working on it now..

The User needs to be an End User (not app user) with these roles:

      'Standard SERVICEABILITY Administration',
      'Standard CCM Admin Users',
      'Standard AXL API Access',
      'Standard CTI All Control of All Devices',
      'Standard CTI All Control of Phones supporting Connected Xfer and conf',
      'Standard CTI Enabled'

I'm working to setup the Access Control Group to set the functional roles for you using Verify/Set Permissions..but haven't finished it yet..
