### ISSUE TITLE
Background macro not working on OSX

### ISSUE THREAD

**Issue by jkittle** [drkchiloll/IMPERIUM#2]
See attachment, when i select the phones for the macro for background, they don't display.

<img width="1347" alt="screen shot 2018-11-11 at 1 44 07 pm" src="https://user-images.githubusercontent.com/1580195/48316918-f101c100-e5b7-11e8-84a1-89ea03e1c0a5.png">

**Comment by drkchiloll** [comment]
Enabled Web Access on your phones...the biggest drawback to controlling a device "you typically might not be able to see"...ensure Enterprise Params Authentication URL (non-secure/secure is pointed to a url the phones have reachability to)
